---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
words: Tom,Dick,Peter,Drew
  
---
spring:
  profiles: verb
words: punched,kicked,kissed,threw

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: lovely,abominable,ferocious,timid,lively

---
spring:
  profiles: noun
words: snow-man,beast,dragon,gollum,ghost
